### PR TITLE
Add "exmachina" process/privilege separation layer for configuration management

### PR DESCRIPTION
**Pull request by bnewbold**
IMPORTANT: this code has NOT actually been tested on a  DreamPlug or in the FreedomBox environment

Changes:
- add exmachina code and test code
- modify plinth.py to listen for shared secret on stdin at start
  (if appropriate flag is set) and try to connect to exmachina daemon
- use exmachina to read and set /etc/hostname as a demo
- update plinth init.d script to start exmachina and share keys
- update docs with new deps and run instructions

Notes:
- using a name ("exmachina") is kind of over-doing things, but that component could be split out in the future
- see separate repository at https://github.com/bnewbold/exmachina for easier review

ToDo:
- add --group argument, chgrp, and 0660 permissions on socket file
- add apt-get package installation/removal methods
- add/handle one or two common non-augeas configuration methods (eg, timezone?)
- use /var/lib/exmachina/<something> as socket instead of /tmp/exmachina.sock?

### CODE REVIEW

**Comment by jvasile** [comment]
I will test on my dreamplug and merge shortly.

**Comment by bnewbold** [comment]
Nick said:

Also, I took a look at the ExMachinaHandler, and you could simplify it a
lot by making it inherit from the Augeas class as well, there'd be no
need for the wrappers.  Otherwise, you can probably do some fancy magic
with getattribute.  I'd duckduck for something on "pass through", but I
haven't figured out how to prevent it from recursing infinitely when the
wrapped object doesn't have the attribute (because you're calling
getattribute on the current object from within its getattribute
function).

**Comment by bnewbold** [comment]
Improvements to exmachina (see https://github.com/bnewbold/exmachina/commits/master/):

remove deprecated optparse
pep8 compliance (mostly)
add group flag
apt-get wrappers
add timezone setting hook

**Comment by NickDaly** [comment]
Bryan, I've merged and pushed this branch in my master.  We'll see what it does for the weekly images!

https://github.com/NickDaly/Plinth/commits/master

**Pull request merged**
